"""Initial schema

Revision ID: 75b3e07ac518
Revises: 
Create Date: 2026-01-24 06:53:56.182004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b3e07ac518'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_country'), table_name='error_events')
    op.drop_index(op.f('idx_error_events_compound'), table_name='error_events')
    op.drop_index(op.f('idx_error_events_country'), table_name='error_events')
    op.drop_index(op.f('idx_error_events_timestamp'), table_name='error_events')
    op.drop_index(op.f('idx_timestamp'), table_name='error_events')
    op.drop_index(op.f('idx_timestamp_country'), table_name='error_events')
    op.drop_index(op.f('idx_word'), table_name='error_events')
    op.create_index(op.f('ix_error_events_country_code'), 'error_events', ['country_code'], unique=False)
    op.create_index(op.f('ix_error_events_id'), 'error_events', ['id'], unique=False)
    op.create_index(op.f('ix_error_events_timestamp'), 'error_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_error_events_word'), 'error_events', ['word'], unique=False)
    op.create_index(op.f('ix_fetch_logs_id'), 'fetch_logs', ['id'], unique=False)
    op.drop_index(op.f('idx_news_articles_published'), table_name='news_articles')
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_skipped_events_id'), 'skipped_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skipped_events_id'), table_name='skipped_events')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.create_index(op.f('idx_news_articles_published'), 'news_articles', ['published_at'], unique=False)
    op.drop_index(op.f('ix_fetch_logs_id'), table_name='fetch_logs')
    op.drop_index(op.f('ix_error_events_word'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_timestamp'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_id'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_country_code'), table_name='error_events')
    op.create_index(op.f('idx_word'), 'error_events', ['word'], unique=False)
    op.create_index(op.f('idx_timestamp_country'), 'error_events', ['timestamp', 'country_code'], unique=False)
    op.create_index(op.f('idx_timestamp'), 'error_events', ['timestamp'], unique=False)
    op.create_index(op.f('idx_error_events_timestamp'), 'error_events', ['timestamp'], unique=False)
    op.create_index(op.f('idx_error_events_country'), 'error_events', ['country_code'], unique=False)
    op.create_index(op.f('idx_error_events_compound'), 'error_events', ['timestamp', 'country_code'], unique=False)
    op.create_index(op.f('idx_country'), 'error_events', ['country_code'], unique=False)
    # ### end Alembic commands ###
